### ISSUE TITLE
Can't even start the thing

### ISSUE THREAD

**Issue by jaymanser1999** [sentanos/roblox-js-server#25]
Every time I start Heroku I get this immediately get: 

2017-02-09T17:03:34.303742+00:00 heroku[web.1]: State changed from crashed to starting
2017-02-09T17:03:35.907374+00:00 heroku[web.1]: Starting process with command `npm start`
2017-02-09T17:03:38.681741+00:00 app[web.1]: 
2017-02-09T17:03:38.681758+00:00 app[web.1]: > roblox-js-server@1.2.0 start /app
2017-02-09T17:03:38.681759+00:00 app[web.1]: > node server.js
2017-02-09T17:03:38.681760+00:00 app[web.1]: 
2017-02-09T17:03:39.310574+00:00 app[web.1]: module.js:590
2017-02-09T17:03:39.310588+00:00 app[web.1]:     throw err;
2017-02-09T17:03:39.310589+00:00 app[web.1]:     ^
2017-02-09T17:03:39.310590+00:00 app[web.1]: 
2017-02-09T17:03:39.310591+00:00 app[web.1]: SyntaxError: /app/settings.json: Unexpected token 
2017-02-09T17:03:39.310592+00:00 app[web.1]:  in JSON at position 89
2017-02-09T17:03:39.310593+00:00 app[web.1]:     at Object.parse (native)
2017-02-09T17:03:39.310593+00:00 app[web.1]:     at Object.Module._extensions..json (module.js:587:27)
2017-02-09T17:03:39.310594+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-09T17:03:39.310595+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-09T17:03:39.310596+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-02-09T17:03:39.310596+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-09T17:03:39.310597+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-09T17:03:39.310598+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:11:16)
2017-02-09T17:03:39.310598+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-09T17:03:39.310599+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-02-09T17:03:39.310599+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-09T17:03:39.310600+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-09T17:03:39.310601+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-02-09T17:03:39.310601+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-02-09T17:03:39.310602+00:00 app[web.1]:     at run (bootstrap_node.js:394:7)
2017-02-09T17:03:39.310602+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-02-09T17:03:39.310603+00:00 app[web.1]:     at bootstrap_node.js:509:3
2017-02-09T17:03:39.323336+00:00 app[web.1]: 
2017-02-09T17:03:39.334289+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-02-09T17:03:39.334621+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-02-09T17:03:39.334907+00:00 app[web.1]: npm ERR! node v6.9.5
2017-02-09T17:03:39.335138+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-02-09T17:03:39.335380+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-02-09T17:03:39.335564+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-02-09T17:03:39.335732+00:00 app[web.1]: npm ERR! Exit status 1
2017-02-09T17:03:39.336025+00:00 app[web.1]: npm ERR! 
2017-02-09T17:03:39.336116+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script 'node server.js'.
2017-02-09T17:03:39.336257+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-02-09T17:03:39.336342+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the roblox-js-server package,
2017-02-09T17:03:39.336427+00:00 app[web.1]: npm ERR! not with npm itself.
2017-02-09T17:03:39.336571+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-02-09T17:03:39.336659+00:00 app[web.1]: npm ERR!     node server.js
2017-02-09T17:03:39.336744+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-02-09T17:03:39.336824+00:00 app[web.1]: npm ERR!     npm bugs roblox-js-server
2017-02-09T17:03:39.336910+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-02-09T17:03:39.336989+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-02-09T17:03:39.337073+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-02-09T17:03:39.340393+00:00 app[web.1]: 
2017-02-09T17:03:39.340564+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-02-09T17:03:39.340631+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-02-09T17:03:39.392755+00:00 heroku[web.1]: Process exited with status 1
2017-02-09T17:03:39.403418+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-09T17:03:39.336659+00:00 app[web.1]: npm ERR!     node server.js
2017-02-09T17:03:39.336744+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-02-09T17:03:39.336824+00:00 app[web.1]: npm ERR!     npm bugs roblox-js-server
2017-02-09T17:03:39.336910+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-02-09T17:03:39.336989+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-02-09T17:03:39.337073+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-02-09T17:03:39.340393+00:00 app[web.1]: 
2017-02-09T17:03:39.340564+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-02-09T17:03:39.340631+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-02-09T17:03:39.392755+00:00 heroku[web.1]: Process exited with status 1
2017-02-09T17:03:39.403418+00:00 heroku[web.1]: State changed from starting to crashed

I do not know that much about nodeJS, if you could please help.

**Comment by sentanos** [comment]
You configured your settings.json incorrectly, make sure username, password, and key are in between quotes and do not contain quotes that are unescaped.

**Comment by jaymanser1999** [comment]
^

I feel REALLY, REALLY DUMB. The settings were 100% correct, I had my text editor open all day and forgot the "save button" was a thing. To much RBX.LUA and its auto-save 👎
