### ISSUE TITLE
"HTTP 502 (HTTP/1.1 502 Bad Gateway)" on ROBLOX File. HELP NEEDED

### ISSUE THREAD

**Issue by 1coolblockhead** [sentanos/roblox-js-server#33]
Hi. 
Whenever I try to run the file on ROBLOX with correct settings and everything from what I see in the documentation, I always keep receiving "HTTP 502 (HTTP/1.1 502 Bad Gateway)" in the console, both in-game and in editor. HTTP is enabled. I have tried to fix it and nothing seems to work. Please help.

**Comment by 1coolblockhead** [comment]
By the way, this is for a group acceptance center so a working script would be helpful if the issue is not easily fixable.

**Comment by sentanos** [comment]
Make sure the heroku app is even up. If you go to the URL in your browser you should see "Cannot get /". If you see anything else it could mean your server isn't set up correctly.

**Comment by 1coolblockhead** [comment]
[https://apr-atm.herokuapp.com/](url) That is the URL but it isn't working. What now?

**Comment by 1coolblockhead** [comment]
![screen shot 2017-06-08 at 1 09 42 pm](https://user-images.githubusercontent.com/23383828/26928301-ee5f3416-4c55-11e7-81ea-a6566ce988d4.png)

**Comment by sentanos** [comment]
Redo the installation process from the beginning, making sure to follow the instructions exactly.

**Comment by 1coolblockhead** [comment]
created a new server at https://gac-main.herokuapp.com/

**Comment by 1coolblockhead** [comment]
Says the same thing when i retry.

**Comment by sentanos** [comment]
I don't know what to tell you other than you are probably setting it up incorrectly because there is no other reason this would happen.

**Comment by 1coolblockhead** [comment]
Hmm. Would you mind setting one up for me then cause I am following instructions exactly. I'm using Terminal on my mac so maybe that could cause an issue. I truthfully don't know.

**Comment by sentanos** [comment]
Post a screenshot of the application logs here: https://dashboard.heroku.com/apps/gac-main/logs
If you don't see anything or it's cut off go to More > Restart All Dynos and then take a screenshot once the logs fill up.

**Comment by 1coolblockhead** [comment]
Created a new app. Same problems. Here is the log:

2017-06-14T10:55:17.496710+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-06-14T10:55:17.496883+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-14T10:55:17.501610+00:00 app[web.1]: 
2017-06-14T10:55:17.501819+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-14T10:55:17.501898+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-14T10:55:17.464265+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-14T10:55:17.464263+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-14T10:55:17.588774+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-14T10:55:17.575869+00:00 heroku[web.1]: Process exited with status 1
2017-06-15T21:46:27.371357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=816e46b6-d8e2-4328-9d22-3ad6f6e7370f fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-15T21:46:29.204074+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=9206cc3f-718c-46c9-b6bc-50204dd57d55 fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-14T10:55:17.496710+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-06-14T10:55:17.496883+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-14T10:55:17.501610+00:00 app[web.1]: 
2017-06-14T10:55:17.501819+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-14T10:55:17.501898+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-14T10:55:17.464265+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-14T10:55:17.464263+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-14T10:55:17.588774+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-14T10:55:17.575869+00:00 heroku[web.1]: Process exited with status 1
2017-06-15T21:46:27.371357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=816e46b6-d8e2-4328-9d22-3ad6f6e7370f fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-15T21:46:29.204074+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=9206cc3f-718c-46c9-b6bc-50204dd57d55 fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-14T10:55:17.496710+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-06-14T10:55:17.496883+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-14T10:55:17.501610+00:00 app[web.1]: 
2017-06-14T10:55:17.501819+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-14T10:55:17.501898+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-14T10:55:17.464265+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-14T10:55:17.464263+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-14T10:55:17.588774+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-14T10:55:17.575869+00:00 heroku[web.1]: Process exited with status 1
2017-06-15T21:46:27.371357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=816e46b6-d8e2-4328-9d22-3ad6f6e7370f fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-15T21:46:29.204074+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=9206cc3f-718c-46c9-b6bc-50204dd57d55 fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-20T09:27:50.378888+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=3faced53-ba87-42c9-8631-beb153f6615c fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:27:51.686846+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=aa974033-d19a-4ae9-882e-ab7d7f34e037 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:28:02.198767+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/promote/3193649/113217491" host=apr-atm.herokuapp.com request_id=f22fe030-a93a-4248-85fe-f8b13a0158c6 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-14T10:55:17.501819+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-14T10:55:17.501898+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-14T10:55:17.464265+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-14T10:55:17.464263+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-14T10:55:17.588774+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-14T10:55:17.575869+00:00 heroku[web.1]: Process exited with status 1
2017-06-15T21:46:27.371357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=816e46b6-d8e2-4328-9d22-3ad6f6e7370f fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-15T21:46:29.204074+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=9206cc3f-718c-46c9-b6bc-50204dd57d55 fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-20T09:27:50.378888+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=3faced53-ba87-42c9-8631-beb153f6615c fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:27:51.686846+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=aa974033-d19a-4ae9-882e-ab7d7f34e037 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:28:02.198767+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/promote/3193649/113217491" host=apr-atm.herokuapp.com request_id=f22fe030-a93a-4248-85fe-f8b13a0158c6 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http

**Comment by sentanos** [comment]
Make sure you are getting ALL the logs including those right after restart. The logs you posted don't make much sense because there isn't a real error message in them.

**Comment by 1coolblockhead** [comment]
Restarted it and all logs.

2017-06-14T10:55:17.464265+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-14T10:55:17.464263+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-14T10:55:17.588774+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-14T10:55:17.575869+00:00 heroku[web.1]: Process exited with status 1
2017-06-15T21:46:27.371357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=816e46b6-d8e2-4328-9d22-3ad6f6e7370f fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-15T21:46:29.204074+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=9206cc3f-718c-46c9-b6bc-50204dd57d55 fwd="72.24.111.94" dyno= connect= service= status=503 bytes= protocol=https
2017-06-20T09:27:50.378888+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=3faced53-ba87-42c9-8631-beb153f6615c fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:27:51.686846+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=aa974033-d19a-4ae9-882e-ab7d7f34e037 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T09:28:02.198767+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/promote/3193649/113217491" host=apr-atm.herokuapp.com request_id=f22fe030-a93a-4248-85fe-f8b13a0158c6 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T12:18:55.301669+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apr-atm.herokuapp.com request_id=e8c888fb-e523-4358-8598-a308faa911bd fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T12:18:56.021736+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apr-atm.herokuapp.com request_id=7df98e33-4d93-45f0-8f48-f8484c6bafb6 fwd="141.31.171.242" dyno= connect= service= status=503 bytes= protocol=http
2017-06-20T12:19:20.314467+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-20T12:19:22.558906+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-20T12:19:25.993216+00:00 app[web.1]: 
2017-06-20T12:19:25.993241+00:00 app[web.1]: > roblox-js-server@1.2.0 start /app
2017-06-20T12:19:25.993242+00:00 app[web.1]: > node server.js
2017-06-20T12:19:25.993243+00:00 app[web.1]: 
2017-06-20T12:19:27.097366+00:00 app[web.1]: module.js:590
2017-06-20T12:19:27.097378+00:00 app[web.1]:     throw err;
2017-06-20T12:19:27.097378+00:00 app[web.1]:     ^
2017-06-20T12:19:27.097379+00:00 app[web.1]: 
2017-06-20T12:19:27.097380+00:00 app[web.1]: SyntaxError: /app/settings.json: Unexpected token “ in JSON at position 16
2017-06-20T12:19:27.097381+00:00 app[web.1]:     at Object.parse (native)
2017-06-20T12:19:27.097382+00:00 app[web.1]:     at Object.Module._extensions..json (module.js:587:27)
2017-06-20T12:19:27.097383+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-20T12:19:27.097383+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-20T12:19:27.097384+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-20T12:19:27.097385+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-06-20T12:19:27.097385+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-20T12:19:27.097386+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:11:16)
2017-06-20T12:19:27.097386+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-20T12:19:27.097387+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-20T12:19:27.097387+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-20T12:19:27.097388+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-20T12:19:27.097388+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-20T12:19:27.097389+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-06-20T12:19:27.097389+00:00 app[web.1]:     at run (bootstrap_node.js:389:7)
2017-06-20T12:19:27.097390+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-06-20T12:19:27.097390+00:00 app[web.1]:     at bootstrap_node.js:504:3
2017-06-20T12:19:27.116805+00:00 app[web.1]: 
2017-06-20T12:19:27.134886+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-06-20T12:19:27.135186+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-06-20T12:19:27.135406+00:00 app[web.1]: npm ERR! node v6.11.0
2017-06-20T12:19:27.135625+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-06-20T12:19:27.135832+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-20T12:19:27.136008+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-06-20T12:19:27.136137+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-20T12:19:27.136276+00:00 app[web.1]: npm ERR! 
2017-06-20T12:19:27.136416+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script 'node server.js'.
2017-06-20T12:19:27.136559+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-06-20T12:19:27.136696+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the roblox-js-server package,
2017-06-20T12:19:27.137005+00:00 app[web.1]: npm ERR! not with npm itself.
2017-06-20T12:19:27.137153+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-06-20T12:19:27.137283+00:00 app[web.1]: npm ERR!     node server.js
2017-06-20T12:19:27.137428+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-06-20T12:19:27.137565+00:00 app[web.1]: npm ERR!     npm bugs roblox-js-server
2017-06-20T12:19:27.137696+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-06-20T12:19:27.137819+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-06-20T12:19:27.137948+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-20T12:19:27.147779+00:00 app[web.1]: 
2017-06-20T12:19:27.148056+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-20T12:19:27.148210+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-20T12:19:27.260028+00:00 heroku[web.1]: Process exited with status 1
2017-06-20T12:19:27.275185+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-20T12:19:27.276189+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-20T12:19:29.034436+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-20T12:19:31.647932+00:00 app[web.1]: 
2017-06-20T12:19:31.647947+00:00 app[web.1]: > roblox-js-server@1.2.0 start /app
2017-06-20T12:19:31.647948+00:00 app[web.1]: > node server.js
2017-06-20T12:19:31.647948+00:00 app[web.1]: 
2017-06-20T12:19:32.422593+00:00 app[web.1]: module.js:590
2017-06-20T12:19:32.422603+00:00 app[web.1]:     throw err;
2017-06-20T12:19:32.422604+00:00 app[web.1]:     ^
2017-06-20T12:19:32.422604+00:00 app[web.1]: 
2017-06-20T12:19:32.422605+00:00 app[web.1]: SyntaxError: /app/settings.json: Unexpected token “ in JSON at position 16
2017-06-20T12:19:32.422606+00:00 app[web.1]:     at Object.parse (native)
2017-06-20T12:19:32.422607+00:00 app[web.1]:     at Object.Module._extensions..json (module.js:587:27)
2017-06-20T12:19:32.422608+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-20T12:19:32.422608+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-20T12:19:32.422609+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-20T12:19:32.422610+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-06-20T12:19:32.422610+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-20T12:19:32.422611+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:11:16)
2017-06-20T12:19:32.422612+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-20T12:19:32.422612+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-20T12:19:32.422613+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-20T12:19:32.422613+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-20T12:19:32.422614+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-20T12:19:32.422614+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-06-20T12:19:32.422615+00:00 app[web.1]:     at run (bootstrap_node.js:389:7)
2017-06-20T12:19:32.422616+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-06-20T12:19:32.422616+00:00 app[web.1]:     at bootstrap_node.js:504:3
2017-06-20T12:19:32.433750+00:00 app[web.1]: 
2017-06-20T12:19:32.441276+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-06-20T12:19:32.441532+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-06-20T12:19:32.441676+00:00 app[web.1]: npm ERR! node v6.11.0
2017-06-20T12:19:32.441806+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-06-20T12:19:32.441942+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-20T12:19:32.442048+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-06-20T12:19
:32.442200+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-20T12:19:32.442346+00:00 app[web.1]: npm ERR! 
2017-06-20T12:19:32.442483+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script 'node server.js'.
2017-06-20T12:19:32.442614+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-06-20T12:19:32.442749+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the roblox-js-server package,
2017-06-20T12:19:32.442998+00:00 app[web.1]: npm ERR! not with npm itself.
2017-06-20T12:19:32.443137+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-06-20T12:19:32.443270+00:00 app[web.1]: npm ERR!     node server.js
2017-06-20T12:19:32.443404+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-06-20T12:19:32.443531+00:00 app[web.1]: npm ERR!     npm bugs roblox-js-server
2017-06-20T12:19:32.443663+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-06-20T12:19:32.443790+00:00 app[web.1]: npm ERR!     npm owner ls roblox-js-server
2017-06-20T12:19:32.443921+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-20T12:19:32.447210+00:00 app[web.1]: 
2017-06-20T12:19:32.447407+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-20T12:19:32.447517+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-20T12:19:32.523169+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-20T12:19:32.512043+00:00 heroku[web.1]: Process exited with status 1

**Comment by sentanos** [comment]
Post a screenshot your settings.json with username and password blocked out, the problem is there.

**Comment by 1coolblockhead** [comment]
![screen shot 2017-06-20 at 4 58 48 pm](https://user-images.githubusercontent.com/23383828/27340063-ca838122-55d9-11e7-81ba-7d0a87eae0d3.png)

**Comment by sentanos** [comment]
What happened was your text editor changed the normal quotes to "smart quotes" which break the script. See how the ones around username and password are curly? Copy the one that is not curly and replace those quotes (or disable smart quotes in your text editor)

**Comment by 1coolblockhead** [comment]
Thanks

**Comment by 1coolblockhead** [comment]
Issue is fixed but now it is saying "HTTP 503 (HTTP/1.1 503 Service Unavailable)

**Comment by sentanos** [comment]
Check your logs again.

**Comment by 1coolblockhead** [comment]
2017-06-21T06:25:27.236918+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-21T06:25:29.313354+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-21T06:25:31.577321+00:00 heroku[web.1]: Process exited with status 1
2017-06-21T06:25:31.405442+00:00 app[web.1]: 
2017-06-21T06:25:31.405468+00:00 app[web.1]: > roblox-js-server@1.2.0 start /app
2017-06-21T06:25:31.405469+00:00 app[web.1]: > node server.js
2017-06-21T06:25:31.405470+00:00 app[web.1]: 
2017-06-21T06:25:31.478854+00:00 app[web.1]: module.js:471
2017-06-21T06:25:31.478856+00:00 app[web.1]:     throw err;
2017-06-21T06:25:31.478857+00:00 app[web.1]:     ^
2017-06-21T06:25:31.478858+00:00 app[web.1]: 
2017-06-21T06:25:31.478859+00:00 app[web.1]: Error: Cannot find module 'express'
2017-06-21T06:25:31.478860+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-06-21T06:25:31.478861+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-06-21T06:25:31.478861+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-06-21T06:25:31.478862+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-21T06:25:31.478862+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:1:77)
2017-06-21T06:25:31.478863+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-21T06:25:31.478863+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-21T06:25:31.478864+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-21T06:25:31.478865+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-21T06:25:31.478865+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-21T06:25:31.495575+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-21T06:25:31.495819+00:00 app[web.1]: npm ERR! errno 1
2017-06-21T06:25:31.495987+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-06-21T06:25:31.496106+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-21T06:25:31.496422+00:00 app[web.1]: npm ERR! 
2017-06-21T06:25:31.496561+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script.
2017-06-21T06:25:31.496685+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-06-21T06:25:31.497724+00:00 app[web.1]: 
2017-06-21T06:25:31.497913+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-06-21T06:25:31.498016+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-06-21T06_25_31_490Z-debug.log
2017-06-21T06:25:31.590158+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-21T06:25:31.591406+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-21T06:25:34.131035+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-21T06:25:37.106675+00:00 heroku[web.1]: Process exited with status 1
2017-06-21T06:25:36.873113+00:00 app[web.1]: 
2017-06-21T06:25:36.873128+00:00 app[web.1]: > roblox-js-server@1.2.0 start /app
2017-06-21T06:25:36.873129+00:00 app[web.1]: > node server.js
2017-06-21T06:25:36.873130+00:00 app[web.1]: 
2017-06-21T06:25:36.980566+00:00 app[web.1]: module.js:471
2017-06-21T06:25:36.980568+00:00 app[web.1]:     throw err;
2017-06-21T06:25:36.980569+00:00 app[web.1]:     ^
2017-06-21T06:25:36.980570+00:00 app[web.1]: 
2017-06-21T06:25:36.980571+00:00 app[web.1]: Error: Cannot find module 'express'
2017-06-21T06:25:36.980572+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-06-21T06:25:36.980572+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-06-21T06:25:36.980573+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-06-21T06:25:36.980573+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-21T06:25:36.980574+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:1:77)
2017-06-21T06:25:36.980575+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-21T06:25:36.980575+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-21T06:25:36.980576+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-21T06:25:36.980576+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-21T06:25:36.980577+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-06-21T06:25:37.012527+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-21T06:25:37.014207+00:00 app[web.1]: npm ERR! errno 1
2017-06-21T06:25:37.015302+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-06-21T06:25:37.016221+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-21T06:25:37.016461+00:00 app[web.1]: npm ERR! 
2017-06-21T06:25:37.016671+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script.
2017-06-21T06:25:37.018036+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-06-21T06:25:37.020806+00:00 app[web.1]: 
2017-06-21T06:25:37.021053+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-06-21T06:25:37.021185+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-06-21T06_25_37_002Z-debug.log
2017-06-21T06:25:37.125452+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by 1coolblockhead** [comment]
2017-06-21T06:25:37.012527+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-21T06:25:37.014207+00:00 app[web.1]: npm ERR! errno 1
2017-06-21T06:25:37.015302+00:00 app[web.1]: npm ERR! roblox-js-server@1.2.0 start: `node server.js`
2017-06-21T06:25:37.016221+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-21T06:25:37.016461+00:00 app[web.1]: npm ERR! 
2017-06-21T06:25:37.016671+00:00 app[web.1]: npm ERR! Failed at the roblox-js-server@1.2.0 start script.
2017-06-21T06:25:37.018036+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-06-21T06:25:37.020806+00:00 app[web.1]: 
2017-06-21T06:25:37.021053+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-06-21T06:25:37.021185+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-06-21T06_25_37_002Z-debug.log
2017-06-21T06:25:37.125452+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by sentanos** [comment]
You are still setting up the server incorrectly. Do you have a node_modules folder in your app? If you do you shouldn't.
