### ISSUE TITLE
POST getPlayers/make/{groupId} TypeError

### ISSUE THREAD

**Issue by FreeLineTM** [sentanos/roblox-js-server#42]
I was testing out the getPlayers method and then I got an error in the log:
`TypeError: Cannot read property 'then' of undefined
    at getPlayersWithOpt (/home/eirik/workspace/web/trc/trc-roblox-js-server/server.js:275:18)
    at Layer.handle [as handle_request] (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:410:3)
    at next (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/body-parser/lib/types/json.js:112:7)
    at Layer.handle [as handle_request] (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:317:13)
    at /home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/eirik/workspace/web/trc/trc-roblox-js-server/node_modules/express/lib/router/index.js:275:10)`

I fixed this by removing `promise` from `players.promise.then(function (info) {` on line 222.

Just wanted to let you know about the bug and the fix.

**Comment by sentanos** [comment]
Not sure why this is happening. The API was changed in the beta version but roblox-js-server shouldn't be using that.

**Comment by FreeLineTM** [comment]
Hmm.. Well, the getPlayers function from the roblox-js "library" returns a promise, so I don't think you can call promise on it..? But I'm not that experienced with NodeJS. Also I didn't really know if it was fixed in an update because to be honest, I have no clue how I am going to update right now because I have modified the server to fit what I'm using it for..

**Comment by sentanos** [comment]
Right I forgot that was also in the latest release. The reason is because roblox-js-server was only designed to work with v2 of roblox-js, which functioned differently, if you look in the [package.json](https://github.com/sentanos/roblox-js-server/blob/master/package.json#L20) file you can see the dependency is `"roblox-js": "^2.0.0"`. This means if you install the server correctly (with the right dependencies) it should work. You didn't use the heroku setup so I don't know how you did it and you most likely used the wrong version of the library.

**Comment by FreeLineTM** [comment]
I am in fact using the Heroku setup. But I checked my package.json and yes, it is in fact the wrong version. It's at ^3.0.6. Should I change it to 2.0.0 and run npm install and undo the "fix" that I did?

**Comment by sentanos** [comment]
I'm not sure why it is the wrong version, you should not have touched package.json or used npm install at all as heroku would automatically install the correct dependencies for you. What you should do is your choice, though if you leave it you may run into more problems with other.

**Comment by FreeLineTM** [comment]
If I remember correctly, I think ran npm install to have development locally as I am modifying the server as I need to to fit what I am using it for.

**Comment by sentanos** [comment]
In that case you can do what you posted earlier as heroku will default to using your "prebuild".

**Comment by FreeLineTM** [comment]
Alright, thanks. Do I close this now or..? Never used git issues before.
