### ISSUE TITLE
roblox-js GroupPayout "Unhandled rejection Error: Found"

### ISSUE THREAD

**Issue by JonasTheGamer** [sentanos/roblox-js-server#78]
Hey! I got an error which directs to the extension files, not my file. Has anyone else got this? If you want me to give my code, tell me.
I used the 
roblox.groupPayout(groupId,UserId,amount);
However, that throws the following error:
`Unhandled rejection Error: Found
    at C:\Users\jonas\Desktop\MyBot\node_modules\roblox-js\lib\group\groupPayout.js:28:13
    at tryCatcher (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\jonas\Desktop\MyBot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)`

Thanks to whoever can help me out! ;)

**Comment by JonasTheGamer** [comment]
@sentanos Sorry, I forgot to mention. ;)
